--ALTER TABLE [dbo].[PRODUCT_CALENDER]
--ADD CHECK ([CategoryProductId]>=18); 

ALTER TABLE [dbo].[PRODUCT_CALENDER]
DROP CONSTRAINT FK_PRODUCTCALENDER_CATEGORYPRODUCT; 

SELECT 
    OBJECT_NAME(OBJECT_ID) AS NameofConstraint
        ,SCHEMA_NAME(schema_id) AS SchemaName
        ,OBJECT_NAME(parent_object_id) AS TableName
        ,type_desc AS ConstraintType
    FROM sys.objects
    WHERE type_desc LIKE '%CONSTRAINT' and OBJECT_NAME(parent_object_id) ='PRODUCT_CALENDER'

	SELECT * 
    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
    WHERE CONSTRAINT_NAME='FK_PRODUCTCALENDER_CATEGORYPRODUCT'

	ALTER TABLE [dbo].[PRODUCT_CALENDER]  
WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_CALENDER_CategoryProductId] FOREIGN KEY(CategoryProductId)
REFERENCES [dbo].[CATEGORY_PRODUCT] ([Id])
GO

