//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCT_PAYMENT
    {
        public int Id { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<int> AccountNumberId { get; set; }
        public System.DateTime PaidDate { get; set; }
        public int Amount { get; set; }
        public int ParcialAmount { get; set; }
        public string Comment { get; set; }
        public int ReservationId { get; set; }
        public int PaymentStatusId { get; set; }
        public int VendedorId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
