//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTOS_TYPE_PROVIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GASTOS_TYPE_PROVIDER()
        {
            this.GASTOS_OPERATION = new HashSet<GASTOS_OPERATION>();
        }
    
        public int Id { get; set; }
        public int GastosTypeId { get; set; }
        public string Comment { get; set; }
        public int ProviderId { get; set; }
        public int CategoryProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> Populate { get; set; }
    
        public virtual CATEGORY_PRODUCT CATEGORY_PRODUCT { get; set; }
        public virtual GASTOS_TYPE GASTOS_TYPE { get; set; }
        public virtual PROVIDER PROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GASTOS_OPERATION> GASTOS_OPERATION { get; set; }
    }
}
