//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Worker_Detail
    {
        public int Id { get; set; }
        public Nullable<int> DateMonthId { get; set; }
        public Nullable<double> Sueldo_SBU { get; set; }
        public Nullable<double> Fondos_de_reserva { get; set; }
        public Nullable<double> Bonos { get; set; }
        public Nullable<double> Excedente { get; set; }
        public Nullable<double> Horas_Extras { get; set; }
        public Nullable<double> Otros_Ingresos { get; set; }
        public Nullable<double> Vacaciones { get; set; }
        public Nullable<double> Decimo_tercero { get; set; }
        public Nullable<double> Decimo_Cuarto { get; set; }
        public Nullable<double> IESS_empleador { get; set; }
        public Nullable<double> Total_ingresos { get; set; }
        public Nullable<double> IESS_trabajador { get; set; }
        public Nullable<double> Impuesto_a_la_Renta { get; set; }
        public Nullable<double> IESS_Prestamos { get; set; }
        public Nullable<double> Anticipos { get; set; }
        public Nullable<double> Prestamos_Internos { get; set; }
        public Nullable<double> Total_descuentos { get; set; }
        public Nullable<double> Total_a_pagar { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string Attachment { get; set; }
        public string ArchiveAttachment { get; set; }
    }
}
