//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Itinerary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Itinerary()
        {
            this.I_Sales = new HashSet<I_Sales>();
        }
    
        public int Id { get; set; }
        public int ICategoryPlaceId { get; set; }
        public int IProvideId { get; set; }
        public int IDaysId { get; set; }
        public decimal Price { get; set; }
        public string MeetingPoint { get; set; }
        public string StartTourTime { get; set; }
        public string EndTourTime { get; set; }
        public string Included { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual I_CategoryPlace I_CategoryPlace { get; set; }
        public virtual I_Days I_Days { get; set; }
        public virtual I_Proveedor I_Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Sales> I_Sales { get; set; }
    }
}
