//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_CALENDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_CALENDER()
        {
            this.PRODUCT_CALENDERHOUR = new HashSet<PRODUCT_CALENDERHOUR>();
            this.PRODUCT_RESERVATION = new HashSet<PRODUCT_RESERVATION>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryProductId { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public Nullable<int> TotalBooks { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Tourdays { get; set; }
    
        public virtual CATEGORY_PRODUCT CATEGORY_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_CALENDERHOUR> PRODUCT_CALENDERHOUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_RESERVATION> PRODUCT_RESERVATION { get; set; }
    }
}
