//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetPaxList
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Passport { get; set; }
        public string Agencia { get; set; }
        public string Agente { get; set; }
        public string PAGO { get; set; }
        public Nullable<int> ProductCalenderId { get; set; }
        public int Id { get; set; }
    }
}
