//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ACCT_CAJACHICA")]
    public class ACCT_CAJACHICA
    {
        public int Id { get; set; }
        public System.DateTime PerDate { get; set; }
        public Nullable<int> NrFactura { get; set; }
        public string Provider { get; set; }
        public string Description { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> RetencionProcent { get; set; }
        public Nullable<decimal> TotalRetencion { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal Balance { get; set; }
        public int PeriodId { get; set; }
    }
}
