//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ACCT_CAJACHICA_RESERVATION")]
    public class ACCT_CAJACHICA_RESERVATION
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public Nullable<int> TypePaymentId { get; set; }
        public Nullable<int> NrPayment { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountLastMonth { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<short> Status { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
    }
}
