//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
namespace SalesApp.Models.Entities
{
   
    [Table("CATEGORY_PRODUCT")]
    public class CATEGORY_PRODUCT
    {
        public CATEGORY_PRODUCT()
        {
            this.GASTOS_TYPE_PROVIDER = new HashSet<GASTOS_TYPE_PROVIDER>();
            this.PRODUCT_CALENDER = new HashSet<PRODUCT_CALENDER>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public Nullable<bool> Lock { get; set; }
    
        [ForeignKey("CategoryId")]
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GASTOS_TYPE_PROVIDER> GASTOS_TYPE_PROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_CALENDER> PRODUCT_CALENDER { get; set; }
    }
}
