//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("COUNTRY")]
    public class COUNTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUNTRY()
        {
            this.ADRESS = new HashSet<ADRESS>();
        }
    
        public int Id { get; set; }
        public string continent { get; set; }
        public string Name { get; set; }
        public string capital { get; set; }
        public string iso2 { get; set; }
        public string iso3 { get; set; }
        public string ioc { get; set; }
        public string tld { get; set; }
        public string currency { get; set; }
        public string phone { get; set; }
        public Nullable<int> Lang_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADRESS> ADRESS { get; set; }
    }
}
