//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public class I_SalesGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_SalesGroup()
        {
            this.I_Sales = new HashSet<I_Sales>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string WhatsAppName { get; set; }
        public int MemberNumberId { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> ItineraryDays { get; set; }
        public int AgentId { get; set; }
        public string DeletedBy { get; set; }
        public string ModifyBy { get; set; }
        public bool Ready { get; set; }
        public Nullable<decimal> TotalPricePaxs { get; set; }
        public Nullable<decimal> TotalPriceSale { get; set; }

        [ForeignKey("AgentId")]
        public virtual I_Agent I_Agent { get; set; }
        [ForeignKey("MemberNumberId")]
        public virtual I_MembersNumber I_MembersNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
     
        public virtual ICollection<I_Sales> I_Sales { get; set; }
    }
}
