//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesApp.Models.Entities
{
    [Table("PRODUCT_CALENDER")]
    public class PRODUCT_CALENDER
    {
         public PRODUCT_CALENDER()
        {
            this.PRODUCT_CALENDERHOUR = new HashSet<PRODUCT_CALENDERHOUR>();
            this.PRODUCT_RESERVATION = new HashSet<PRODUCT_RESERVATION>();
        //    this.CATEGORY_PRODUCTS = new HashSet<CATEGORY_PRODUCT>();
        }

        public int Id { get; set; }
        public int CategoryProductId { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public Nullable<int> TotalBooks { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Tourdays { get; set; }

        [ForeignKey("CategoryProductId")]
        public virtual CATEGORY_PRODUCT CATEGORY_PRODUCT { get; set; }

        public virtual ICollection<PRODUCT_CALENDERHOUR> PRODUCT_CALENDERHOUR { get; set; }

    //    public virtual ICollection<CATEGORY_PRODUCT> CATEGORY_PRODUCTS { get; set; }

        public virtual ICollection<PRODUCT_RESERVATION> PRODUCT_RESERVATION { get; set; }
    }
}
